name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build the project
        run: npm run build
        
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e
