name: Publish to production

on:
  push:
    branches:
      - production

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test

      - name: Run e2e tests
        run: npm run test:e2e

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v2

      - name: Deploy to Heroku Action
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            NODE_ENV
            PORT
        env:
          NODE_ENV: production